/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package telas;

import classes.Exemplar;
import enumeradores.EnumAcao;
import interfaces.ICRUDExemplar;
import controle.ControleExemplar;
import utilidades.Mensagens;
import interfaces.ITelaCadastro;
import java.text.DecimalFormat;
import java.text.SimpleDateFormat;
import java.util.Date;
import javafx.scene.chart.PieChart;

/**
 *
 * @author Vinicius
 */
public class TelaExemplar extends javax.swing.JDialog implements ITelaCadastro {

//----------------ATRIBUTOS----------------------------------
//ESSES ATRIBUTOS SAO PWRCORIDOS PELO SISTEMA 
    //CLASSES--------------->
    //ENUMERADORES---------->
    //INTERFACE------------>
    //PERSISTENCIA-------->
    //CONTROLE----------->
    private int id;
    private EnumAcao acao = null;
    private ICRUDExemplar controleExemplar = null;
    private Mensagens mensagens = null;
    private Exemplar exemplar = null;
    private boolean visible = false;
    private Date dataAquisicao = null;
//---------------------end atributos-----------------------
//override

    @Override
    public void setId(int id) {
        this.id = id;
        //isto e o id que vai percorrer cada uma das telas
    }

    @Override
    public void setAcao(EnumAcao acao) {
        this.acao = acao;
        this.setTitle(acao.toString() + " cadastro exemplar");
        // isto chama a açao para ser sequenciada dentro do cadastro exemeplar
        // poer isso o metodo IAtelaCadastro 
        // void setId(int id);
        // void setAcao(EnumAcao acao);
        // void setVisible(boolean b);

    }

    @Override
    public void setVisible(boolean b) {
        try {
            controleExemplar = new ControleExemplar();
            mensagens = new Mensagens();
            if (acao.equals(EnumAcao.Incluir)) {
                limpaTudo();
            } else if (acao.equals(EnumAcao.Editar)) {
                exemplar = controleExemplar.buscarPeloId(id);
                prenecherTudo();
            }
        } catch (Exception e) {
            mensagens.erro(e);
        }
        visible = true;
        super.setVisible(b);
    }
    //--------------------end override------------------------------
    //metodos 

    //validador de prenchimentos dos campos
    public void validardataAquisicao() throws Exception {
        Date data = new Date(jTextFielddataAquisicao.getText().trim());
        //fonte :https://www.devmedia.com.br/manipulando-datas-em-java/21765

        SimpleDateFormat dataDigitada = new SimpleDateFormat("dd/MM/yyyy");
        if (dataDigitada.DATE_FIELD == 0) {
            jTextFielddataAquisicao.requestFocus();
            throw new Exception("imforme a data de aquisão do exemplar");
            //vai pegar a data digitaca pelo usuario que vai ser convertida 
        }
    }

    public void validarprecoCompra() throws Exception {
        DecimalFormat df = new DecimalFormat();
        df.applyPattern("R$ 0.00");
    }

    private void limpaTudo() {
        jTextFieldIDExemplar.setText("");
        jTextFielddataAquisicao.setText("");
        jTextAreamotivoDesativado.setText("");

    }
    
    private void prenecherTudo(){
         jTextFieldIDExemplar.setText(String.format("%04d", exemplar.getIdExemplar()));
        jTextFielddataAquisicao.setText(String.format("dd/MM/yyyy", exemplar.getDataAquisicao()));
        jTextAreamotivoDesativado.setText(String.format("%04d", jTextAreamotivoDesativado));
    }
     private void salvar() throws Exception {
        try {
            validardataAquisicao();
            validarprecoCompra();

            exemplar = new Exemplar();
//            exemplar.setDataAquisicao(jTextFielddataAquisicao.getText());

            if (acao.equals(EnumAcao.Incluir)) {
                controleExemplar.incluir(exemplar);
                mensagens.sucesso("Exemplar incluído com sucesso!");
            } else if (acao.equals(EnumAcao.Editar)) {
                exemplar.setIdExemplar(Integer.parseInt(jTextFieldIDExemplar.getText()));
                controleExemplar.alterar(exemplar);
                mensagens.sucesso("Exemplar alterado com sucesso!");
            }

            visible = false;
            this.dispose();

        } catch (Exception e) {
            mensagens.erro(new Exception("Erro ao salvar: \n" + e));
        
        
        }

    public TelaExemplar(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField1 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jTextFieldIDExemplar = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        jComboBoxstatusExemplar = new javax.swing.JComboBox<>();
        jTextFieldprecoCompra = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextAreamotivoDesativado = new javax.swing.JTextArea();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jTextFielddataAquisicao = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jComboBoxLivro = new javax.swing.JComboBox<>();
        jButtonSalvar = new javax.swing.JButton();

        jTextField1.setText("jTextField1");

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setText("ID");

        jTextFieldIDExemplar.setEditable(false);
        jTextFieldIDExemplar.setText("                          ");
        jTextFieldIDExemplar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldIDExemplarActionPerformed(evt);
            }
        });

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Exemplar "));

        jTextFieldprecoCompra.setText("      ");

        jLabel6.setText("Motivo da  desativação ");

        jTextAreamotivoDesativado.setColumns(20);
        jTextAreamotivoDesativado.setRows(2);
        jTextAreamotivoDesativado.setToolTipText("");
        jScrollPane1.setViewportView(jTextAreamotivoDesativado);

        jLabel2.setText("Livro");

        jLabel3.setText("Status  ");

        jLabel4.setText("Data da aquisição ");

        jTextFielddataAquisicao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFielddataAquisicaoActionPerformed(evt);
            }
        });

        jLabel5.setText("Preço da compra  ");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel2)
                                            .addComponent(jLabel5)
                                            .addComponent(jComboBoxLivro, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(20, 20, 20)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel3)
                                            .addComponent(jComboBoxstatusExemplar, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(jTextFielddataAquisicao, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel4)))
                                    .addComponent(jTextFieldprecoCompra, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addComponent(jScrollPane1))
                        .addContainerGap())))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jComboBoxstatusExemplar, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFielddataAquisicao, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBoxLivro, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextFieldprecoCompra, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(9, 9, 9)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jButtonSalvar.setText("Salvar");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(20, 20, 20))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                            .addComponent(jButtonSalvar)
                            .addGap(20, 20, 20))
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jLabel1)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(jTextFieldIDExemplar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(481, 481, 481)))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jTextFieldIDExemplar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButtonSalvar)
                .addGap(20, 20, 20))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextFieldIDExemplarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldIDExemplarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldIDExemplarActionPerformed

    private void jTextFielddataAquisicaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFielddataAquisicaoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFielddataAquisicaoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaExemplar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaExemplar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaExemplar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaExemplar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                TelaExemplar dialog = new TelaExemplar(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonSalvar;
    private javax.swing.JComboBox<String> jComboBoxLivro;
    private javax.swing.JComboBox<String> jComboBoxstatusExemplar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextAreamotivoDesativado;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextFieldIDExemplar;
    private javax.swing.JTextField jTextFielddataAquisicao;
    private javax.swing.JTextField jTextFieldprecoCompra;
    // End of variables declaration//GEN-END:variables

}
